server:
  port: 8080
app:
  test: 123
  token: "6173129634:AAH5-V1AvHyXpW3GItK8GSRWaWy5AWIfdys"
springdoc:
  api-docs:
    enabled: true
    path: /openapi/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui